/* Generated By:JavaCC: Do not edit this line. MetroCompilerConstants.java */
package metrocompiler.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MetroCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_LINEA = 5;
  /** RegularExpression Id. */
  int PUNTO_COMA = 6;
  /** RegularExpression Id. */
  int COMA = 7;
  /** RegularExpression Id. */
  int SELECCIONAR = 8;
  /** RegularExpression Id. */
  int VIAJE = 9;
  /** RegularExpression Id. */
  int PAGAR = 10;
  /** RegularExpression Id. */
  int DEVOLVER = 11;
  /** RegularExpression Id. */
  int RECARGAR = 12;
  /** RegularExpression Id. */
  int TARJETA = 13;
  /** RegularExpression Id. */
  int PREPAGO = 14;
  /** RegularExpression Id. */
  int DESCONTAR = 15;
  /** RegularExpression Id. */
  int SIMPLE = 16;
  /** RegularExpression Id. */
  int DOBLE = 17;
  /** RegularExpression Id. */
  int TURISTICO = 18;
  /** RegularExpression Id. */
  int NUMERO_DECIMAL = 19;
  /** RegularExpression Id. */
  int CODIGO_TARJETA = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<COMENTARIO_LINEA>",
    "\";\"",
    "\",\"",
    "\"SELECCIONAR\"",
    "\"VIAJE\"",
    "\"PAGAR\"",
    "\"DEVOLVER\"",
    "\"RECARGAR\"",
    "\"TARJETA\"",
    "\"PREPAGO\"",
    "\"DESCONTAR\"",
    "\"simple\"",
    "\"doble\"",
    "<TURISTICO>",
    "<NUMERO_DECIMAL>",
    "<CODIGO_TARJETA>",
  };

}
